// <auto-generated />
namespace Gestion.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddComisionRevendedores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddComisionRevendedores));
        
        string IMigrationMetadata.Id
        {
            get { return "201312231526200_AddComisionRevendedores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
