// <auto-generated />
namespace Gestion.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Valor2NotRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Valor2NotRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201402131809206_Valor2NotRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
